stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 include/vector_nav/registers.h
    - cpplint --verbose=0 include/vector_nav/vector_nav.h
    - cpplint --verbose=0 include/vector_nav/vn.h
    - cpplint --verbose=0 include/vector_nav/vn100.h
    - cpplint --verbose=0 include/vector_nav/vn200.h
    - cpplint --verbose=0 include/vector_nav/vn300.h
    - cpplint --verbose=0 src/vector_nav/vn100.cc
    - cpplint --verbose=0 src/vector_nav/vn200.cc
    - cpplint --verbose=0 src/vector_nav/vn300.cc

  